<a href="https://colab.research.google.com/github/afullhart/climateanalogs/blob/main/Figures/Tables.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
%reset -f

### Imports

In [22]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

### ZeroOne Ecoregion Lvl 3 Accuracy

In [18]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


fld = '/content/drive/My Drive/Colab Notebooks/Analogs/Binary_Test'

files = [f for f in os.listdir(fld) if f[-4:] == '.csv']
print(files)


test_groups = ['34', '125671012', '101114', '81315', '912']
diag_group = [['14', '81'], ['13', '20', '22', '24'], ['5', '18', '19', '21', '80'], ['23', '79'], ['25', '26']]


df_dict = {}
for n in test_groups:
  df = pd.read_csv(os.path.join(fld, 'Zonal_eco3_{}.csv'.format(n)))
  mask = df.iloc[:, 1:].any(axis=1)
  df = df.iloc[:, 1:][mask]
  n_classes = len(df)
  df_dict[n] = df

display(df)

true_positive_rate_list = []
true_negative_rate_list = []
area_norm_list = []
test_scores = []
avg_area_norm = 0.0
for i, df_key in enumerate(df_dict):
  df = df_dict[df_key]
  n = df.sum().sum()
  sum_values_per_col = df.sum()
  codes = ['US_L3_' + diag_group[i][j] for j in range(len(diag_group[i]))]
  anti_codes = [c for c in df.columns.to_list() if c not in codes]
  yes_n = float(df[codes].loc[255, :].sum())
  no_n = float(df[codes].loc[0, :].sum())
  anti_yes_n = float(df[anti_codes].loc[255, :].sum())
  anti_no_n = float(df[anti_codes].loc[0, :].sum())
  area_n = yes_n + no_n
  anti_area_n = anti_yes_n + anti_no_n

  true_positive = yes_n
  true_negative = anti_no_n
  false_positive = anti_yes_n
  false_negative =  no_n

  group_accuracy = (true_positive + true_negative) / (true_positive + true_negative + false_positive + false_negative)
  print(group_accuracy)
  test_scores.append(group_accuracy)
  true_positive_rate = yes_n / (yes_n + no_n)
  true_negative_rate = anti_no_n / (anti_no_n + anti_yes_n)
  true_positive_rate_list.append(true_positive_rate)
  true_negative_rate_list.append(true_negative_rate)
  area_norm = (true_positive_rate + true_negative_rate) / 2.0
  area_norm_list.append(area_norm)
  avg_area_norm += area_norm * (area_n / n)

print(f'Average accuracy score: {np.average(test_scores)*100}')
print(f'Average true positive rate: {np.average(true_positive_rate_list)*100}')
print(f'Average true negative rate: {np.average(true_negative_rate_list)*100}')
print(f'Area-norm classification rate: {np.average(area_norm_list)*100}')
#print(f'Average area-norm classification rate: {avg_area_norm*100}')

['Zonal_mlra_912.csv', 'Zonal_mlra_101114.csv', 'Zonal_eco3_81315.csv', 'Zonal_eco3_34.csv', 'Zonal_eco3_101114.csv', 'Zonal_mlra_15.csv', 'Zonal_mlra_125678.csv', 'Zonal_eco3_912.csv', 'Zonal_eco3_125671012.csv', 'Zonal_mlra_34.csv', 'Zonal_mlra_813.csv']

,US_L3_13,US_L3_14,US_L3_18,US_L3_19,US_L3_20,US_L3_21,US_L3_22,US_L3_23,US_L3_24,US_L3_25,US_L3_26,US_L3_5,US_L3_79,US_L3_80,US_L3_81
0,418401,76411,3662,64570,146992,38167,195033,152034,71140,4,11814,1345,53556,60889,124827
255,26645,10,873,1269,1588,1488,3021,3920,29023,45717,89401,53,708,870,7

0.9753135013471411
0.8180269280379048
0.8251285235407819
0.9030606650823746
0.9499254052202795
Average accuracy score: 89.42910046456964
Average true positive rate: 83.86382003889365
Average true negative rate: 91.43628028273247
Area-norm classification rate: 87.65005016081305

### ZeroOne MLRA Accuracy

In [19]:

import os
import pandas as pd
import matplotlib.pyplot as plt


fld = '/content/drive/My Drive/Colab Notebooks/Analogs/Binary_Test'

files = [f for f in os.listdir(fld) if f[-4:] == '.csv']
print(files)


test_groups = ['34', '125678', '101114', '813', '15', '912']
diag_group = [['30', '40'], ['24', '27', '28A', '29', '34A', '34B', '35', '42B'],
                ['11', '13', '22A', '23', '25', '26', '28B', '36', '46', '47', '48A', '51'], ['38', '41'],
                ['39'], ['42A', '42C', '70A', '70B', '77B', '77C', '77D', '77E']]


df_dict = {}
for n in test_groups:
  df = pd.read_csv(os.path.join(fld, 'Zonal_mlra_{}.csv'.format(n)))
  mask = df.iloc[:, 1:].any(axis=1)
  df = df.iloc[:, 1:][mask]
  n_classes = len(df)
  df_dict[n] = df

display(df)

true_positive_rate_list = []
true_negative_rate_list = []
area_norm_list = []
test_scores = []
avg_area_norm = 0.0
for i, df_key in enumerate(df_dict):
  df = df_dict[df_key]
  n = df.sum().sum()
  sum_values_per_col = df.sum()
  codes = ['MLRAR_' + diag_group[i][j] for j in range(len(diag_group[i]))]
  anti_codes = [c for c in df.columns.to_list() if c not in codes]
  yes_n = float(df[codes].loc[255, :].sum())
  no_n = float(df[codes].loc[0, :].sum())
  anti_yes_n = float(df[anti_codes].loc[255, :].sum())
  anti_no_n = float(df[anti_codes].loc[0, :].sum())
  area_n = yes_n + no_n
  anti_area_n = anti_yes_n + anti_no_n

  true_positive = yes_n
  true_negative = anti_no_n
  false_positive = anti_yes_n
  false_negative =  no_n

  group_accuracy = (true_positive + true_negative) / (true_positive + true_negative + false_positive + false_negative)
  print(group_accuracy)
  test_scores.append(group_accuracy)
  true_positive_rate = yes_n / (yes_n + no_n)
  true_negative_rate = anti_no_n / (anti_no_n + anti_yes_n)
  true_positive_rate_list.append(true_positive_rate)
  true_negative_rate_list.append(true_negative_rate)
  area_norm = (true_positive_rate + true_negative_rate) / 2.0
  area_norm_list.append(area_norm)
  avg_area_norm += area_norm * (area_n / n)

print(f'Average accuracy score: {np.average(test_scores)*100}')
print(f'Average true positive rate: {np.average(true_positive_rate_list)*100}')
print(f'Average true negative rate: {np.average(true_negative_rate_list)*100}')
print(f'Area-norm classification rate: {np.average(area_norm_list)*100}')
#print(f'Average area-norm classification rate: {avg_area_norm*100}')

['Zonal_mlra_912.csv', 'Zonal_mlra_101114.csv', 'Zonal_eco3_81315.csv', 'Zonal_eco3_34.csv', 'Zonal_eco3_101114.csv', 'Zonal_mlra_15.csv', 'Zonal_mlra_125678.csv', 'Zonal_eco3_912.csv', 'Zonal_eco3_125671012.csv', 'Zonal_mlra_34.csv', 'Zonal_mlra_813.csv']

,MLRAR_11,MLRAR_13,MLRAR_22A,MLRAR_23,MLRAR_24,MLRAR_25,MLRAR_26,MLRAR_27,MLRAR_28A,MLRAR_28B,...,MLRAR_46,MLRAR_47,MLRAR_48A,MLRAR_51,MLRAR_70A,MLRAR_70B,MLRAR_77B,MLRAR_77C,MLRAR_77D,MLRAR_77E
0,228,1543,1311,19377,39206,62570,15025,59036,123280,84630,...,2458,73315,40551,1812,1348,649,0,0,0,0
255,37,786,66,147,1186,1618,382,1106,22585,749,...,19,888,1930,25,29930,55782,5817,8661,18505,1083

0.9795316846491022
0.7841793578558071
0.8549527052498528
0.91743745980747
0.9430578107175152
0.9547004008781375
Average accuracy score: 90.5643236526314
Average true positive rate: 73.84748678176507
Average true negative rate: 92.72525924862248
Area-norm classification rate: 83.28637301519377

### Zscore Ecoregion Lvl 3 Accuracy

In [6]:
import numpy as np
import os
import pandas as pd
import matplotlib.pyplot as plt

fld = '/content/drive/My Drive/Colab Notebooks/Analogs/Binary_Test'

files = [f for f in os.listdir(fld) if f[-4:] == '.csv']
print(files)

test_groups = ['134', '2567812', '91115', '9121314', '10']
diag_group = [['14', '81'], ['13', '18', '20', '22', '24'], ['23', '79'], ['5', '19', '21', '80'], ['25', '26']]

df_dict = {}
for n in test_groups:
  df = pd.read_csv(os.path.join(fld, 'Zonal_eco3_{}.csv'.format(n)))
  mask = df.iloc[:, 1:].any(axis=1)
  df = df.iloc[:, 1:][mask]
  n_classes = len(df)
  df_dict[n] = df

display(df)

true_positive_rate_list = []
true_negative_rate_list = []
area_norm_list = []
test_scores = []
for i, df_key in enumerate(df_dict):
  df = df_dict[df_key]
  n = df.sum().sum()
  sum_values_per_col = df.sum()
  codes = ['US_L3_' + diag_group[i][j] for j in range(len(diag_group[i]))]
  anti_codes = [c for c in df.columns.to_list() if c not in codes]
  yes_n = float(df[codes].loc[255, :].sum())
  no_n = float(df[codes].loc[0, :].sum())
  anti_yes_n = float(df[anti_codes].loc[255, :].sum())
  anti_no_n = float(df[anti_codes].loc[0, :].sum())
  area_n = yes_n + no_n
  anti_area_n = anti_yes_n + anti_no_n

  true_positive = yes_n
  true_negative = anti_no_n
  false_positive = anti_yes_n
  false_negative =  no_n

  group_accuracy = (true_positive + true_negative) / (true_positive + true_negative + false_positive + false_negative)
  print(group_accuracy)
  test_scores.append(group_accuracy)
  true_positive_rate = yes_n / (yes_n + no_n)
  true_negative_rate = anti_no_n / (anti_no_n + anti_yes_n)
  true_positive_rate_list.append(true_positive_rate)
  true_negative_rate_list.append(true_negative_rate)
  area_norm = (true_positive_rate + true_negative_rate) / 2.0
  area_norm_list.append(area_norm)

print(f'Average accuracy score: {np.average(test_scores)*100}')
print(f'Average true positive rate: {np.average(true_positive_rate_list)*100}')
print(f'Average true negative rate: {np.average(true_negative_rate_list)*100}')
print(f'Area-norm classification rate: {np.average(area_norm_list)*100}')

['Zonal_eco3_125671012.csv', 'Zonal_eco3_34.csv', 'Zonal_eco3_81315.csv', 'Zonal_eco3_912.csv', 'Zonal_eco3_101114.csv', 'Zonal_mlra_125678.csv', 'Zonal_mlra_34.csv', 'Zonal_mlra_813.csv', 'Zonal_mlra_912.csv', 'Zonal_mlra_101114.csv', 'Zonal_mlra_15.csv', 'Zonal_eco3_134.csv', 'Zonal_eco3_2567812.csv', 'Zonal_eco3_91115.csv', 'Zonal_eco3_9121314.csv', 'Zonal_eco3_10.csv', 'Zonal_mlra_13.csv', 'Zonal_mlra_24568.csv', 'Zonal_mlra_7912.csv', 'Zonal_mlra_10.csv', 'Zonal_mlra_11.csv', 'Zonal_mlra_1314.csv']

,US_L3_13,US_L3_14,US_L3_18,US_L3_19,US_L3_20,US_L3_21,US_L3_22,US_L3_23,US_L3_24,US_L3_25,US_L3_26,US_L3_5,US_L3_79,US_L3_80,US_L3_81
0,349970,76336,2270,61174,132988,35981,156995,139485,70987,4,6484,1321,53555,42179,124827
255,95076,85,2265,4665,15592,3674,41059,16469,29176,45717,94731,77,709,19580,7

0.9294183085525902
0.7086165286262857
0.7161733309187046
0.7435818306581464
0.8552935190626313
Average accuracy score: 79.06167035636716
Average true positive rate: 62.01717325119166
Average true negative rate: 83.82380580552118
Area-norm classification rate: 72.92048952835641

### Zscore MLRA Accuracy

In [7]:

import os
import pandas as pd
import matplotlib.pyplot as plt


fld = '/content/drive/My Drive/Colab Notebooks/Analogs/Binary_Test'

files = [f for f in os.listdir(fld) if f[-4:] == '.csv']
print(files)

test_groups = ['13', '24568', '7912', '10', '11', '1314']
diag_group = [['30', '40'], ['24', '26', '27', '28A', '29', '34B', '35', '42B'],
              ['11', '13', '23', '25', '28B', '34A', '36', '39', '51'], ['42A', '42C', '70A', '70B', '77B', '77C', '77D', '77E'],
              ['38', '41'], ['22A', '46', '47', '48A']]

df_dict = {}
for n in test_groups:
  df = pd.read_csv(os.path.join(fld, 'Zonal_mlra_{}.csv'.format(n)))
  mask = df.iloc[:, 1:].any(axis=1)
  df = df.iloc[:, 1:][mask]
  n_classes = len(df)
  df_dict[n] = df

display(df)

true_positive_rate_list = []
true_negative_rate_list = []
area_norm_list = []
test_scores = []
for i, df_key in enumerate(df_dict):
  df = df_dict[df_key]
  n = df.sum().sum()
  sum_values_per_col = df.sum()
  codes = ['MLRAR_' + diag_group[i][j] for j in range(len(diag_group[i]))]
  anti_codes = [c for c in df.columns.to_list() if c not in codes]
  yes_n = float(df[codes].loc[255, :].sum())
  no_n = float(df[codes].loc[0, :].sum())
  anti_yes_n = float(df[anti_codes].loc[255, :].sum())
  anti_no_n = float(df[anti_codes].loc[0, :].sum())
  area_n = yes_n + no_n
  anti_area_n = anti_yes_n + anti_no_n

  true_positive = yes_n
  true_negative = anti_no_n
  false_positive = anti_yes_n
  false_negative =  no_n

  group_accuracy = (true_positive + true_negative) / (true_positive + true_negative + false_positive + false_negative)
  print(group_accuracy)
  test_scores.append(group_accuracy)
  true_positive_rate = yes_n / (yes_n + no_n)
  true_negative_rate = anti_no_n / (anti_no_n + anti_yes_n)
  true_positive_rate_list.append(true_positive_rate)
  true_negative_rate_list.append(true_negative_rate)
  area_norm = (true_positive_rate + true_negative_rate) / 2.0
  area_norm_list.append(area_norm)

print(f'Average accuracy score: {np.average(test_scores)*100}')
print(f'Average true positive rate: {np.average(true_positive_rate_list)*100}')
print(f'Average true negative rate: {np.average(true_negative_rate_list)*100}')
print(f'Area-norm classification rate: {np.average(area_norm_list)*100}')

['Zonal_eco3_125671012.csv', 'Zonal_eco3_34.csv', 'Zonal_eco3_81315.csv', 'Zonal_eco3_912.csv', 'Zonal_eco3_101114.csv', 'Zonal_mlra_125678.csv', 'Zonal_mlra_34.csv', 'Zonal_mlra_813.csv', 'Zonal_mlra_912.csv', 'Zonal_mlra_101114.csv', 'Zonal_mlra_15.csv', 'Zonal_eco3_134.csv', 'Zonal_eco3_2567812.csv', 'Zonal_eco3_91115.csv', 'Zonal_eco3_9121314.csv', 'Zonal_eco3_10.csv', 'Zonal_mlra_13.csv', 'Zonal_mlra_24568.csv', 'Zonal_mlra_7912.csv', 'Zonal_mlra_10.csv', 'Zonal_mlra_11.csv', 'Zonal_mlra_1314.csv']

,MLRAR_11,MLRAR_13,MLRAR_22A,MLRAR_23,MLRAR_24,MLRAR_25,MLRAR_26,MLRAR_27,MLRAR_28A,MLRAR_28B,...,MLRAR_46,MLRAR_47,MLRAR_48A,MLRAR_51,MLRAR_70A,MLRAR_70B,MLRAR_77B,MLRAR_77C,MLRAR_77D,MLRAR_77E
0,247,2102,285,19074,39936,56051,14965,60100,141296,83302,...,1146,27963,28281,1791,30290,55974,5817,8661,18505,1083
255,18,227,1092,450,456,8137,442,42,4569,2077,...,1331,46240,14200,46,988,457,0,0,0,0

0.8924626532859934
0.6706762693447724
0.6758461682505501
0.7843161048541488
0.8170097250522965
0.8889608213689976
Average accuracy score: 78.82119570261264
Average true positive rate: 27.354548017918468
Average true negative rate: 86.95511336374615
Area-norm classification rate: 57.154830690832306

### Print ZeroOne Diagnostic Groups

In [11]:
import matplotlib.colors as mcolors
import pandas as pd

zonalf = '/content/drive/My Drive/Colab Notebooks/Analogs/Zonal/Zonal_tavg.csv'

colors = ['#91FE28', '#F4714F', '#FF611B', '#FBAF1C', '#F8E019', '#CCFE29', '#BDBEBE', '#00FE24', '#18F2FE', '#3AC2FD', '#5E79FD', '#6E12FC', '#E21DFD', '#FF18A9', '#FF2B18']
cmap = mcolors.ListedColormap(colors)

df = pd.read_csv(zonalf)
df.index.name = 'arc_id'
df['tavg'] = df['MEAN']
df['color'] = colors

temp_order_df = df.sort_values(by='tavg', ascending=False)
df = temp_order_df.reset_index()
arc_to_order_key = dict(zip(df['Value'].to_list(), [int(x+1) for x in df.index]))
print(arc_to_order_key)

test_groupsA = ['34', '125671012', '101114', '81315', '912']
diag_groupsA = [['14', '81'], ['13', '20', '22', '24'], ['5', '18', '19', '21', '80'], ['23', '79'], ['25', '26']]
#diag_groupsA = [[14, 81], [13, 20, 22, 24], [5, 18, 19, 80], [21, 23, 79], [25, 26]]
test_groupsB = ['34', '125678', '101114', '813', '15', '912']
diag_groupsB = [['30', '40'], ['24', '27', '28A', '29', '34A', '34B', '35', '42B'],
                ['11', '13', '22A', '23', '25', '26', '28B', '36', '46', '47', '48A', '51'], ['38', '41'],
                ['39'], ['42A', '42C', '70A', '70B', '77B', '77C', '77D', '77E']]

arc_groupsA = [[3, 4], [1, 2, 5, 6, 7, 10, 12], [10, 11, 14], [8, 13, 15], [9, 10, 12]]
ord_groupsA = []
for g in arc_groupsA:
  g_list = []
  for val in g:
    g_list.append(arc_to_order_key[val])
  ord_groupsA.append(g_list)

print(ord_groupsA)
print(diag_groupsA)

arc_groupsB = [[3, 4], [1, 2, 5, 6, 7, 8], [10, 11, 14], [8, 13], [15], [9, 12]]
ord_groupsB = []
for g in arc_groupsB:
  g_list = []
  for val in g:
    g_list.append(arc_to_order_key[val])
  ord_groupsB.append(g_list)

print(ord_groupsB)
print(diag_groupsB)

{4: 1, 3: 2, 8: 3, 9: 4, 13: 5, 1: 6, 2: 7, 5: 8, 7: 9, 6: 10, 12: 11, 10: 12, 15: 13, 11: 14, 14: 15}
[[2, 1], [6, 7, 8, 10, 9, 12, 11], [12, 14, 15], [3, 5, 13], [4, 12, 11]]
[['14', '81'], ['13', '20', '22', '24'], ['5', '18', '19', '21', '80'], ['23', '79'], ['25', '26']]
[[2, 1], [6, 7, 8, 10, 9, 3], [12, 14, 15], [3, 5], [13], [4, 11]]
[['30', '40'], ['24', '27', '28A', '28B', '29', '34A', '34B', '35', '42B'], ['11', '13', '22A', '23', '25', '26', '36', '46', '47', '48A', '51'], ['38', '41'], ['39'], ['42A', '42C', '70A', '70B', '77B', '77C', '77D', '77E']]

### Print Zscore Diagnostic Groups

### ZO Ecoregion Lvl 4 accuracy

In [40]:
import pandas as pd

zonalf = '/content/drive/My Drive/Colab Notebooks/Analogs/Zonal/Zonal_eco4.csv'

df = pd.read_csv(zonalf)

display(df)

columns = df.columns

col_str = columns[1]
eco4_label = col_str.split('_')[2]

def lvl_label_split(l):
  l = l.split('_')[2]
  return l

def lvl3_label_split(l):
  l = l.split('_')[2]
  numbers = [c for c in l if c.isdigit()]
  numbers = ''.join(numbers)
  return numbers

def lvl4_label_split(l):
  l = l.split('_')[2]
  letters = [c for c in l if c.isalpha()]
  letters = ''.join(letters)
  return letters


lvl_labels = columns[1:].map(lvl_label_split)
lvl3_labels = columns[1:].map(lvl3_label_split)
lvl4_labels = columns[1:].map(lvl4_label_split)

print(lvl_labels)
print(lvl3_labels)
print(lvl4_labels)

,LABEL,US_L4_13a,US_L4_13aa,US_L4_13ac,US_L4_13b,US_L4_13c,US_L4_13d,US_L4_13e,US_L4_13f,US_L4_13g,...,US_L4_80l,US_L4_81d,US_L4_81g,US_L4_81i,US_L4_81j,US_L4_81k,US_L4_81l,US_L4_81m,US_L4_81n,US_L4_81o
0,1,738,45,0,2464,112,0,0,0,208,...,5,0,0,0,0,0,0,0,0,0
1,2,69,739,30,4053,823,110,0,31,84,...,82,0,0,0,0,0,0,0,0,0
2,3,0,0,0,0,0,0,0,0,6,...,0,7,2412,7993,7056,22012,9523,335,5224,1596
3,4,0,0,0,0,0,0,0,0,2,...,0,1077,281,1551,24849,916,15058,754,4175,1128
4,5,614,347,10,13029,4227,16,0,0,106,...,364,0,0,0,0,0,0,0,0,0
5,6,202,3426,40,6925,11322,1588,0,15,31,...,579,0,0,0,0,0,0,0,0,0
6,7,19459,4,0,12105,642,0,0,0,1101,...,100,0,340,2,188,0,0,0,0,0
7,8,0,4,0,8,0,829,0,0,2,...,0,0,0,0,0,9908,8375,0,0,0
8,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,10,168,2078,0,2877,15354,5618,0,129,87,...,204,0,0,0,0,0,0,0,0,0
10,11,5,1265,0,10,2033,13134,2300,32,14,...,6,0,0,0,0,0,0,0,0,0
11,12,8346,357,0,2629,4695,29,0,2977,1411,...,97,0,0,1,0,0,0,0,0,6
12,13,0,3,0,0,18,3401,0,0,0,...,0,0,0,0,0,67,0,0,0,0
13,14,0,39,0,0,490,2225,1726,353,0,...,0,0,0,0,0,0,0,0,0,0
14,15,0,0,0,0,0,637,13,0,0,...,0,0,0,0,0,0,0,0,0,0

Index(['13a', '13aa', '13ac', '13b', '13c', '13d', '13e', '13f', '13g', '13h',
       ...
       '80l', '81d', '81g', '81i', '81j', '81k', '81l', '81m', '81n', '81o'],
      dtype='object', length=152)
Index(['13', '13', '13', '13', '13', '13', '13', '13', '13', '13',
       ...
       '80', '81', '81', '81', '81', '81', '81', '81', '81', '81'],
      dtype='object', length=152)
Index(['a', 'aa', 'ac', 'b', 'c', 'd', 'e', 'f', 'g', 'h',
       ...
       'l', 'd', 'g', 'i', 'j', 'k', 'l', 'm', 'n', 'o'],
      dtype='object', length=152)